### ISSUE TITLE
Sip profile and dialplan being copied unintentionally?

### ISSUE THREAD

**Issue by RyanChimienti** [drachtio/docker-drachtio-freeswitch-base#14]
Hey Dave, quick question--did you intend to add these lines back to the Dockerfile?
```
&& cp /tmp/mrf_dialplan.xml /usr/local/freeswitch/conf/dialplan \
&& cp /tmp/mrf_sip_profile.xml /usr/local/freeswitch/conf/sip_profiles \
```

It looks like they were removed in [this commit](https://github.com/drachtio/docker-drachtio-freeswitch-base/commit/eac2afbbcd0b0528916b8aec1ac1732d4cd60e83) and then reintroduced [here](https://github.com/drachtio/docker-drachtio-freeswitch-base/commit/d499cadf934aff6cf15de4ad7ee0c45877e1d874). This is causing some weirdness in my application because `mrf_sip_profile.xml` conflicts with the `mrf.xml` profile defined in `docker-drachtio-freeswitch-mrf`.

**Comment by davehorton** [comment]
hmm, looks like an error on my part

**Comment by RyanChimienti** [comment]
No worries, thanks for the quick fix!
