### ISSUE TITLE
FreeSWITCH 1.10?

### ISSUE THREAD

**Issue by lylepratt** [drachtio/docker-drachtio-freeswitch-base#2]
I'm thinking about trying to get this image to optionally work with FreeSWITCH 1.10. Curious if you are aware of anything you know will break? Perhaps your custom modules?

**Comment by davehorton** [comment]
got you covered.

```
docker pull drachtio/drachtio-freeswitch-mrf:v1.10.1-full
```
This is built from the `freeswitch-v1.10.1-full` tag in this repo as well as `https://github.com/davehorton/docker-drachtio-freeswitch-mrf`

I will probably merge to the master branch later today

**Comment by lylepratt** [comment]
Nice! thanks!

**Comment by lylepratt** [comment]
@davehorton the `1.10.1-full` branch seems to die on me after it loads OPUS. Immediately after this:
`2020-09-22 14:39:52.738529 [NOTICE] switch_loadable_module.c:412 Adding API Function 'opus_debug'`

I'm going to comment out your opus patch and see if that changes anything.

**Comment by lylepratt** [comment]
Nevermind...the crash was due to me enabling `mod_av` in the branch. Very strange since it compiles without issue and doesn't through an error.

**Comment by lylepratt** [comment]
Going to try to compile against 1.10.5 in the signalwire repo and see if the same thing happens

**Comment by lylepratt** [comment]
No luck that direction either. Can't get `mod_av` to load at all.

I don't get anything super out of the ordinary when it compiles either:
```
making all mod_av
make[4]: Entering directory '/usr/local/src/freeswitch/src/mod/applications/mod_av'
  CC       libavmod_la-mod_av.lo
  CC       libavmod_la-avformat.lo
  CC       libavmod_la-avcodec.lo
  CCLD     libavmod.la
ar: `u' modifier ignored since `D' is the default (see `U')
  CCLD     mod_av.la
  CC       test/test_mod_av.o
  CCLD     test/test_mod_av
/usr/bin/ld: warning: libssl.so.1.0.2, needed by //usr/lib/x86_64-linux-gnu/libcurl.so.4, may conflict with libssl.so.1.1
/usr/bin/ld: warning: libcrypto.so.1.0.2, needed by //usr/lib/x86_64-linux-gnu/libcurl.so.4, may conflict with libcrypto.so.1.1
  CC       test/test_avformat.o
  CCLD     test/test_avformat
/usr/bin/ld: warning: libssl.so.1.0.2, needed by //usr/lib/x86_64-linux-gnu/libcurl.so.4, may conflict with libssl.so.1.1
/usr/bin/ld: warning: libcrypto.so.1.0.2, needed by //usr/lib/x86_64-linux-gnu/libcurl.so.4, may conflict with libcrypto.so.1.1
make[4]: Leaving directory '/usr/local/src/freeswitch/src/mod/applications/mod_av'
```

If anyone has any tips, I'd appreciate it!
