### ISSUE TITLE
When using COPY with more than one source file, the destination must be a directory and end with a /

### ISSUE THREAD

**Issue by tommyNy** [drachtio/docker-drachtio-freeswitch-base#6]
drachtio/drachtio-freeswitch-base:1.10.5

small bug in Dockerfile on Docker version 19.03.5, build 633a0ea838

Step 2/5 : COPY ./files/* /tmp
When using COPY with more than one source file, the destination must be a directory and end with a /
The terminal process "bash '-c', 'docker build --pull --rm -f "Dockerfile" -t drachtio/drachtio-freeswitch-base:1.10.5 "."'" terminated with exit code: 1.

**Comment by lylepratt** [comment]
I had this issue as well. added a `/` on the end of `/tmp` solved it: `/tmp/`
